# Generated by Django 5.0.2 on 2024-03-14 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.PositiveIntegerField()),
                ('userId', models.PositiveIntegerField()),
                ('commentId', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField()),
                ('productId', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Nutriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('unit', models.TextField()),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('nutritionGrade', models.TextField()),
                ('isBeverage', models.BooleanField()),
                ('isCheese', models.BooleanField()),
                ('isFat', models.BooleanField()),
                ('isWater', models.BooleanField()),
                ('weight', models.PositiveIntegerField()),
                ('score', models.TextField()),
                ('imageId', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.PositiveIntegerField()),
                ('userId', models.PositiveIntegerField()),
                ('up', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
