# Generated by Django 5.0.2 on 2024-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.PositiveIntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='origins',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imageId',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nutritionGrade',
            new_name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isBeverage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isCheese',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isFat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isWater',
        ),
        migrations.RemoveField(
            model_name='product',
            name='score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
