# Generated by Django 5.0.2 on 2024-03-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_allergen_category_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity_unit',
            new_name='quantityUnit',
        ),
    ]
