# Generated by Django 5.0.2 on 2024-03-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_quantity_unit_product_quantityunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantityUnit',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
