# Generated by Django 5.0.2 on 2024-03-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
