# Generated by Django 5.0.2 on 2024-03-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_likecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seen',
        ),
    ]
