# Generated by Django 5.0.2 on 2024-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestionId', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('add', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestionId', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('add', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestionId', models.PositiveIntegerField()),
                ('value', models.TextField()),
                ('add', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='suggestionnutriment',
            name='value',
            field=models.TextField(),
        ),
    ]
