# Generated by Django 5.0.2 on 2024-03-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0003_allergen_category_ingredient_nutriment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='SuggestionAllergen',
        ),
        migrations.RenameModel(
            old_name='Allergen',
            new_name='SuggestionCategory',
        ),
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='SuggestionIngredient',
        ),
        migrations.RenameModel(
            old_name='Nutriment',
            new_name='SuggestionNutriment',
        ),
    ]
