# Generated by Django 5.0.2 on 2024-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0004_rename_category_suggestionallergen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionallergen',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suggestioncategory',
            name='name',
            field=models.TextField(),
        ),
    ]
