# Generated by Django 5.0.2 on 2024-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imageId',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
