# Generated by Django 5.0.2 on 2024-03-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_imageid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dietarypref',
            old_name='value',
            new_name='name',
        ),
    ]
